import React from 'react';
import { View, Text, Image, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { SearchBar } from '../components/SearchBar';
import Graph from '../components/Graph'

const Details = () => {
  return (
    <View style={styles.container}>
      <View style={styles.topheader}>
        <Image style={styles.logo} source={require('../assets/images/logo.png')} />
        <Text style={styles.headerText}>Details</Text>
        <SearchBar />
      </View>
      <View style={styles.secheader}>
        <View style={{ flexDirection: 'row' }}>
          <Image style={{ height: 30, width: 30 }} source={require('../assets/images/google.png')} />
          <Text style={styles.headerText}>Google</Text>
        </View>
        <View>
          <Text style={styles.headerText}>$444</Text>
        </View>
      </View>


      <View style={styles.graph}>
        <Graph />
      </View>
    <ScrollView>

      <View style={styles.aboutContainer}>
        <Text style={{ marginLeft: 5, borderBottomWidth:0.5, fontWeight:700, fontSize:16 }}>About Google</Text>

        <ScrollView>
          <View >
            <Text style={{ marginLeft: 5, fontSize:12 }} >International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recines in 1924. IBM is incorporated in New York. IBM produces and sells arch organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s</Text>
          </View>
          <View style={{ flexDirection: 'row', margin: 15 }}>
            <ScrollView horizontal={true}>
              <Text style={styles.chip}>Industory: Electronic Computer</Text>
              <Text style={styles.chip}>Sector: Technology</Text>
            </ScrollView>
          </View>

          {/* stock information */}

          <View style={{ margin: 10, flexDirection: 'row', justifyContent: 'space-between' }}>
            <View>
              <Text style={styles.informationHeading}>52 Week High</Text>
              <Text style={styles.informationHeadingAns}>$1232</Text>
            </View>
            <View style={{ alignItems: 'center' }}>
              <Text style={[styles.informationHeadingAns, { marginBottom: 8 }]}> Current Price $1232</Text>
              <View style={{ width: 125, height: 2, backgroundColor: 'black' }} />
            </View>
            <View>
              <Text style={styles.informationHeading}>52 Week Low</Text>
              <Text style={styles.informationHeadingAns}>$1232</Text>
            </View>

          </View>

          <View style={{ margin: 10, flexDirection: 'row', justifyContent: 'space-between' }}>
            <View>
              <Text style={styles.informationHeading}>Market Cap</Text>
              <Text style={styles.informationHeadingAns}>$1232</Text>
            </View>
            <View>
              <Text style={styles.informationHeading}>Profit Margin</Text>
              <Text style={styles.informationHeadingAns}>$1232</Text>
            </View>
            <View>
              <Text style={styles.informationHeading}>Beta</Text>
              <Text style={styles.informationHeadingAns}>$1232</Text>
            </View>

          </View>

          <View style={{ margin: 10, flexDirection: 'row', marginBottom: 30 }}>
            <View style={{ marginRight: 55 }}>
              <Text style={styles.informationHeading}>Dividend Yield</Text>
              <Text style={styles.informationHeadingAns}>$1232</Text>
            </View>
            <View>
              <Text style={styles.informationHeading}>P/E Ratio</Text>
              <Text style={styles.informationHeadingAns}>$1232</Text>
            </View>

          </View>

        </ScrollView>


      </View>

 </ScrollView>


    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white'

  },
  topheader: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor:'black',

  },
  logo: {
    height: 40,
    width: 40,
  },
  headerText: {
    color: 'black',
    alignSelf: 'center',
    fontSize: 20,
    fontWeight: '500',
    marginLeft: 8,
    marginRight: 30,
  },
  secheader: {
    flexDirection: 'row',
    marginLeft: 30,
    marginTop: 20,
    justifyContent: 'space-between'
  },
  aboutContainer: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'grey',
    marginLeft: 20,
    marginRight: 20,
    borderRadius: 5

  },
  graph: {
    margin: 20
  },
  chip: {
    backgroundColor: '#edd4c6',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
  },
  informationHeading: {
    fontWeight: '700',
    fontSize: 14,
    color: 'black'
  },
  informationHeadingAns: {
    fontWeight: '500',
    fontSize: 13,
    color: 'black'
  }
})


export default Details;